import Foundation

nonisolated struct UserThemeDescriptor: Identifiable, Hashable, Sendable {
    let id: String
    let name: String
    let appearance: String
    let fileURL: URL
}

nonisolated struct ThemeFileService: Sendable {
    static var themesDirectory: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appending(path: "Rafu/Themes", directoryHint: .isDirectory)
    }

    @concurrent
    func installedThemes() async throws -> [UserThemeDescriptor] {
        let directory = Self.themesDirectory
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let urls = try FileManager.default.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        )
        return urls.filter { $0.pathExtension.lowercased() == "json" }.compactMap { url in
            guard let data = try? Data(contentsOf: url),
                let theme = try? JSONDecoder().decode(RafuTheme.self, from: data)
            else { return nil }
            return UserThemeDescriptor(
                id: "user:\(url.lastPathComponent)",
                name: theme.name,
                appearance: theme.appearance,
                fileURL: url
            )
        }
        .sorted { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
    }

    @concurrent
    func importTheme(from source: URL) async throws -> UserThemeDescriptor {
        let data = try Data(contentsOf: source, options: .mappedIfSafe)
        let theme = try JSONDecoder().decode(RafuTheme.self, from: data)
        try validate(theme)
        let directory = Self.themesDirectory
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let filename = uniqueFilename(base: sanitized(theme.name), in: directory)
        let destination = directory.appending(path: filename)
        try data.write(to: destination, options: .atomic)
        return .init(
            id: "user:\(filename)",
            name: theme.name,
            appearance: theme.appearance,
            fileURL: destination
        )
    }

    /// Imports theme JSON supplied as raw data (e.g. generated by an AI
    /// provider) after full decode + validation.
    @concurrent
    func importThemeData(_ data: Data) async throws -> UserThemeDescriptor {
        let theme = try JSONDecoder().decode(RafuTheme.self, from: data)
        try validate(theme)
        let directory = Self.themesDirectory
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let filename = uniqueFilename(base: sanitized(theme.name), in: directory)
        let destination = directory.appending(path: filename)
        try data.write(to: destination, options: .atomic)
        return .init(
            id: "user:\(filename)",
            name: theme.name,
            appearance: theme.appearance,
            fileURL: destination
        )
    }

    @concurrent
    func createCopy(from source: URL, named name: String) async throws -> UserThemeDescriptor {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { throw ThemeFileError.invalidName }
        let data = try Data(contentsOf: source, options: .mappedIfSafe)
        var object = try JSONSerialization.jsonObject(with: data) as? [String: Any] ?? [:]
        object["name"] = trimmed
        object["id"] =
            "dev.rafu.user-theme.\(sanitized(trimmed).replacingOccurrences(of: ".json", with: ""))"
        let updated = try JSONSerialization.data(
            withJSONObject: object,
            options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        )
        let theme = try JSONDecoder().decode(RafuTheme.self, from: updated)
        try validate(theme)
        let directory = Self.themesDirectory
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let filename = uniqueFilename(base: sanitized(trimmed), in: directory)
        let destination = directory.appending(path: filename)
        try updated.write(to: destination, options: .atomic)
        return .init(
            id: "user:\(filename)",
            name: theme.name,
            appearance: theme.appearance,
            fileURL: destination
        )
    }

    private func validate(_ theme: RafuTheme) throws {
        guard !theme.name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw ThemeFileError.invalidName
        }
        guard ["light", "dark"].contains(theme.appearance) else {
            throw ThemeFileError.invalidAppearance
        }
        let colors =
            [
                theme.ui.appBackground,
                theme.ui.editorBackground,
                theme.ui.elevatedBackground,
                theme.ui.textPrimary,
                theme.ui.textSecondary,
                theme.ui.accent,
                theme.ui.borderSubtle,
                theme.ui.selection,
                theme.editor.background,
                theme.editor.foreground,
                theme.editor.cursor,
                theme.editor.selectionBackground,
                theme.editor.lineHighlight,
            ] + theme.syntax.values.compactMap(\.color)
            + theme.syntax.values.compactMap(\.background)
        guard colors.allSatisfy(Self.isHexColor) else {
            throw ThemeFileError.invalidColor
        }
    }

    private static func isHexColor(_ value: String) -> Bool {
        let scalars = value.unicodeScalars
        guard scalars.count == 7 || scalars.count == 9, scalars.first == "#" else {
            return false
        }
        let hexadecimal = CharacterSet(charactersIn: "0123456789abcdefABCDEF")
        return scalars.dropFirst().allSatisfy(hexadecimal.contains)
    }

    private func sanitized(_ name: String) -> String {
        let allowed = name.lowercased().map { character -> Character in
            if character.isLetter || character.isNumber || character == "-" { return character }
            return "-"
        }
        let value = String(allowed).replacingOccurrences(of: "--", with: "-")
        return (value.isEmpty ? "theme" : value) + ".json"
    }

    private func uniqueFilename(base: String, in directory: URL) -> String {
        let stem = (base as NSString).deletingPathExtension
        var filename = base
        var suffix = 2
        while FileManager.default.fileExists(atPath: directory.appending(path: filename).path) {
            filename = "\(stem)-\(suffix).json"
            suffix += 1
        }
        return filename
    }
}

enum ThemeFileError: LocalizedError {
    case invalidName
    case invalidAppearance
    case invalidColor

    var errorDescription: String? {
        switch self {
        case .invalidName: "Enter a theme name."
        case .invalidAppearance: "Theme appearance must be light or dark."
        case .invalidColor: "Theme color tokens must use hexadecimal strings."
        }
    }
}
