import Foundation

/// Constants for the CLI ↔ app versioned same-user Unix-domain socket
/// protocol (ADR 0009, `docs/plans/phases/cli-app-ipc.md`). Frozen by the
/// lane's I0 contract commit — every later increment (framing codec,
/// listener actor, router, CLI client) builds against these values without
/// changing them.
public enum LauncherIPCProtocol {
    /// The 1-byte version carried by every frame's header (`"RAFU"` magic +
    /// this byte + a 4-byte big-endian body length). Bumped only for a
    /// breaking change to the framing bytes themselves, independent of
    /// `protocolVersion` below.
    public static let wireVersion = 1

    /// The envelope/schema version carried inside the JSON body. Bumped for
    /// a breaking change to `LauncherIPCEnvelope`'s shape; new optional
    /// fields do not require a bump (forward-compatible decoding).
    public static let protocolVersion = 1

    /// Upper bound on one framed JSON body, enforced by both the encoder and
    /// the incremental decoder (landed in I1). Paths, line/column, and
    /// activation metadata only — this socket never carries document text
    /// or secrets, so 64 KiB is generous headroom, not a working limit.
    public static let maxFrameBytes = 64 * 1_024
}

/// One request or response frame's discriminator. `handshake` establishes
/// protocol/version compatibility before any `openFolder`/`goto` request;
/// `openFolder` and `goto` both carry a `LauncherOpenRequest` payload (the
/// same value type `LauncherArgumentParser` already produces — this
/// protocol reuses it rather than introducing a parallel shape).
///
/// Decoding never throws on an unrecognized kind: an unknown wire value
/// becomes `.unknown(rawValue)` so a version-skewed peer gets a typed
/// `rejected` response instead of a crash or a dropped connection.
public enum LauncherIPCRequestKind: Hashable, Sendable {
    case handshake
    case openFolder
    case goto
    case unknown(String)
}

extension LauncherIPCRequestKind: Codable {
    public init(from decoder: any Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        switch raw {
        case "handshake": self = .handshake
        case "openFolder": self = .openFolder
        case "goto": self = .goto
        default: self = .unknown(raw)
        }
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .handshake: try container.encode("handshake")
        case .openFolder: try container.encode("openFolder")
        case .goto: try container.encode("goto")
        case .unknown(let raw): try container.encode(raw)
        }
    }
}

/// One request frame's JSON body. `Decodable`'s default keyed-container
/// behavior already tolerates JSON fields this type doesn't declare, so a
/// newer CLI/app pair can add optional fields later without breaking an
/// older peer mid-rollout — no custom decoding is needed for that
/// forward-compatibility guarantee.
public struct LauncherIPCEnvelope: Codable, Hashable, Sendable {
    public let wireVersion: Int
    public let protocolVersion: Int
    /// Correlates a response to its request over the same connection.
    /// Generated by the sender; echoed back unchanged by the receiver.
    public let requestID: String
    public let kind: LauncherIPCRequestKind
    /// `nil` for `handshake`; present for `openFolder`/`goto`.
    public let payload: LauncherOpenRequest?

    public init(
        kind: LauncherIPCRequestKind,
        payload: LauncherOpenRequest? = nil,
        requestID: String = UUID().uuidString,
        wireVersion: Int = LauncherIPCProtocol.wireVersion,
        protocolVersion: Int = LauncherIPCProtocol.protocolVersion
    ) {
        self.wireVersion = wireVersion
        self.protocolVersion = protocolVersion
        self.requestID = requestID
        self.kind = kind
        self.payload = payload
    }
}

/// The app's reply to one `LauncherIPCEnvelope`. `waitSupported` is always
/// `false` in v1 — `--wait` is honestly deferred to v2 (ADR 0009); the CLI
/// uses this field rather than hardcoding the deferral so a v2 app can
/// advertise support without a CLI-side protocol-version branch.
public enum LauncherIPCResponse: Codable, Hashable, Sendable {
    case accepted(workspaceMatched: Bool, windowFocused: Bool, waitSupported: Bool)
    case rejected(reason: String)
}

/// Resolves the deterministic, same-user socket path both the CLI and the
/// app compute independently — no negotiation, no lookup file. Well under
/// the 104-byte `sockaddr_un.sun_path` limit for any real home directory;
/// `LauncherSocketAddress` still guards the limit explicitly at connect
/// time in case a relocated home ever pushes it over.
public enum LauncherIPCSocketPath {
    /// The real per-user Application Support directory. Tests inject a
    /// temporary directory via `resolve(baseDirectory:)` instead, so this
    /// resolver never touches `~/Library/Application Support` outside the
    /// running app/CLI.
    public static var defaultBaseDirectory: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
    }

    /// `<baseDirectory>/Rafu/ipc/v1.sock`. The `v1` path segment is the
    /// protocol's on-disk namespace, not `LauncherIPCProtocol.wireVersion`
    /// re-encoded — a future incompatible wire format gets a new segment
    /// (`v2`) so old and new app builds never fight over one socket file.
    public static func resolve(
        baseDirectory: URL = LauncherIPCSocketPath.defaultBaseDirectory
    ) -> URL {
        baseDirectory
            .appending(path: "Rafu", directoryHint: .isDirectory)
            .appending(path: "ipc", directoryHint: .isDirectory)
            .appending(path: "v1.sock", directoryHint: .notDirectory)
    }
}
